### ISSUE TITLE
[BUG] EventNode.remove() null Exception

### ISSUE THREAD

**Issue by SimonTellier** [mohammedX6/poly_bool_dart#5]
NoSuchMethodError: The setter 'next=' was called on null.
Receiver: null
Tried calling: next=null

**Comment by SimonTellier** [comment]
in your class EventNode -> In your function remove(). you can't do 

```
prev = null;
next = null;
```

A value of type 'Null' can't be assigned to a variable of type 'EventNode'

I am working on GoogleMap and polygons. I'm trying to create an algorithm that would create a polygon that would show the area made by tractors in the fields. Farmers often pass by the same place. So I need the polygon union algorithm to have a surface without overlay. I can share my test code with you so you can see the errors. 

I also have this as a warning 
```
The library 'package:poly_bool_dart/polybool.dart' is legacy, and shouldn't be imported into a null safe library.
Try migrating the imported library.dart[import_of_legacy_library_into_null_safe](https://dart.dev/diagnostics/import_of_legacy_library_into_null_safe)
```

**Comment by SimonTellier** [comment]
I am in version poly_bool_dart: ^0.1.0

**Comment by mohammedX6** [comment]
Please make sure you using version 0.2.0 that has been migrated to null safety

https://pub.dev/packages/polybool

**Comment by SimonTellier** [comment]
Ok, it's better but not perfect.
Can you explain me this : 
```
  throw Exception(
              "PolyBool: Zero-length segment detected; your epsilon is probably too small or too large");
```
I don't have my second polygon added to the main one. I had this error sometimes on the other version

**Comment by mohammedX6** [comment]
Please take a look her : https://github.com/velipso/polybooljs#epsilon

**Comment by mohammedX6** [comment]
What do you mean by foreground and background?
